name: Update Index
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

concurrency: ci-secrets-${{ github.ref }}

permissions:
  contents: write
  security-events: read

jobs:
  update-index:
    name: Update Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

#      - name: run
#        uses: actions-rs/cargo@v1
#        env:
#          SECRET_SCANNING_TOKEN: ${{ secrets.SECRET_SCANNING_TOKEN }}
#        with:
#          command: run
#          args: --release
#
#      - uses: EndBug/add-and-commit@v9
#        with:
#          add: 'README.md'
#          # From https://github.community/t/github-actions-bot-email-address/17204/5
#          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
#          author_name: "commit-bot"
#          message: "Scheduled data update from Github Actions"
#          push: true
#          fetch: false
